import { createApp } from "vue";
import App from "./App.vue";
import plugins from "./plugins";
import store from "./store";
import router from "./router";
const app = createApp(App);
// app.config.ignoredElements = ["wx-open-launch-weapp"];
app.use(plugins);
app.use(store);
app.use(router);
app.mount("#app");
